# Generated by Django 4.2.2 on 2023-07-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KathmanduTourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image_path', models.ImageField(upload_to='images/home/kathmandu_tour/')),
            ],
        ),
        migrations.CreateModel(
            name='PopularDestinationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image_path', models.ImageField(upload_to='images/home/popular_destination/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=40)),
                ('home_main_image', models.ImageField(upload_to='images/home')),
                ('kathmandu_tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.kathmandutourmodel')),
                ('popular_destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.populardestinationmodel')),
            ],
        ),
    ]
