# Generated by Django 4.2.2 on 2023-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homemodel',
            name='kathmandu_tour',
        ),
        migrations.RemoveField(
            model_name='homemodel',
            name='popular_destination',
        ),
        migrations.AddField(
            model_name='homemodel',
            name='kathmandu_tour',
            field=models.ManyToManyField(to='app.kathmandutourmodel'),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='popular_destination',
            field=models.ManyToManyField(to='app.populardestinationmodel'),
        ),
    ]
